# https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/
# https://leetcode.com/problems/integer-replacement/
# https://leetcode.com/problems/max-consecutive-ones/
# https://leetcode.com/problems/find-mode-in-binary-search-tree/
# https://leetcode.com/problems/freedom-trail/
# https://leetcode.com/problems/longest-word-in-dictionary-through-deleting/
# https://leetcode.com/problems/maximum-average-subarray-i/
# https://leetcode.com/problems/find-duplicate-subtrees/
# https://leetcode.com/problems/non-decreasing-array/
# https://leetcode.com/problems/24-game/
# https://leetcode.com/problems/redundant-connection-ii/
# https://leetcode.com/problems/my-calendar-iii/
# https://leetcode.com/problems/daily-temperatures/
# https://leetcode.com/problems/swim-in-rising-water/
# https://leetcode.com/problems/reaching-points/
# https://leetcode.com/problems/escape-the-ghosts/
# https://leetcode.com/problems/domino-and-tromino-tiling/
# https://leetcode.com/problems/soup-servings/
# https://leetcode.com/problems/largest-sum-of-averages/
# https://leetcode.com/problems/find-and-replace-in-string/
# https://leetcode.com/problems/keys-and-rooms/
# https://leetcode.com/problems/shortest-path-visiting-all-nodes/
# https://leetcode.com/problems/k-similar-strings/
# https://leetcode.com/problems/max-area-of-island/
# https://leetcode.com/problems/accounts-merge/
# https://leetcode.com/problems/range-module/
# https://leetcode.com/problems/count-square-submatrices-with-all-ones/
# https://leetcode.com/problems/minimum-window-subsequence/ (https://anshika-bhargava0202.medium.com/leetcode-727-minimum-window-subsequence-21c40baff689)
# https://leetcode.com/problems/bulls-and-cows/
# https://leetcode.com/problems/path-with-minimum-effort/
# https://leetcode.com/problems/minimum-difference-between-largest-and-smallest-value-in-three-moves/
# https://leetcode.com/problems/flip-equivalent-binary-trees/
#